# Generated by Django 4.0.5 on 2022-10-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('prize_type', models.CharField(choices=[('perpc', 'per piece'), ('perkg', 'per kilogram')], default='perkg', max_length=5)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total_prize', models.IntegerField()),
                ('crop', models.ManyToManyField(to='index.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='index.user')),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='index.user')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cropcategory')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cropcategory'),
        ),
    ]
